name: Update CI

on:
  workflow_dispatch:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    container: node:latest

    services:
      echo:
        image: hashicorp/http-echo
        ports:
          - 8080:5678

    steps:
      - run: curl -v http://echo:8080
