name: Update CI

on:
  workflow_dispatch:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node:latest

    services:
      echo:
        image: hashicorp/http-echo
        ports:
          - 80:5678

    steps:
      - uses: actions/checkout@v1
      - run: ls
      - run: curl http://echo
