name: Update CI

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      echo-service:
        image: hashicorp/http-echo
        ports:
          - 80:5678:5678

    steps:
      - run: curl http://echo-service
